#!/bin/sh
# update_cacert.sh — refresh the embedded CA root bundle from curl.se
#
# Fetches Mozilla's CA bundle (as published by the curl project), verifies
# its SHA-256, and regenerates pocketfox_cacert.h. The generated header is
# committed to the repo so vintage targets never need to run this script.
#
# Run from the repo root:  sh tools/update_cacert.sh
# Requires: curl (or wget), sha256sum, awk — i.e. any modern Linux/CI box.

set -e

PEM_URL="https://curl.se/ca/cacert.pem"
SHA_URL="https://curl.se/ca/cacert.pem.sha256"
PEM="certs/cacert.pem"
HDR="pocketfox_cacert.h"

cd "$(dirname "$0")/.."
mkdir -p certs

echo "[cacert] fetching $PEM_URL"
if command -v curl >/dev/null 2>&1; then
    curl -sSL -o "$PEM" "$PEM_URL"
    curl -sSL -o "$PEM.sha256" "$SHA_URL"
else
    wget -q -O "$PEM" "$PEM_URL"
    wget -q -O "$PEM.sha256" "$SHA_URL"
fi

echo "[cacert] verifying SHA-256"
( cd certs && sha256sum -c cacert.pem.sha256 )

CERTS=$(grep -c "BEGIN CERTIFICATE" "$PEM")
DATE=$(sed -n 's/^## Certificate data from Mozilla as of: //p' "$PEM" | head -1)
echo "[cacert] $CERTS certificates, Mozilla data date: ${DATE:-unknown}"

echo "[cacert] generating $HDR"
{
    printf '/*\n'
    printf ' * pocketfox_cacert.h — embedded Mozilla CA root bundle\n'
    printf ' *\n'
    printf ' * AUTO-GENERATED by tools/update_cacert.sh — DO NOT EDIT BY HAND.\n'
    printf ' * Source: %s\n' "$PEM_URL"
    printf ' * Mozilla data date: %s\n' "${DATE:-unknown}"
    printf ' * Certificates: %s\n' "$CERTS"
    printf ' *\n'
    printf ' * PEM cert blocks only (descriptive text stripped to save space).\n'
    printf ' * sizeof() includes the trailing NUL, which mbedtls_x509_crt_parse\n'
    printf ' * requires to be counted in the buffer length for PEM input.\n'
    printf ' */\n'
    printf '#ifndef POCKETFOX_CACERT_H\n'
    printf '#define POCKETFOX_CACERT_H\n\n'
    printf 'static const char pocketfox_cacert_pem[] =\n'
    awk '/-----BEGIN CERTIFICATE-----/{p=1} p{printf "\"%s\\n\"\n", $0} /-----END CERTIFICATE-----/{p=0}' "$PEM"
    printf ';\n\n'
    printf '#endif /* POCKETFOX_CACERT_H */\n'
} > "$HDR"

echo "[cacert] wrote $HDR ($(wc -c < "$HDR") bytes)"
